generator: admingenerator.generator.doctrine
params:
    model: Angie\BlogBundle\Entity\Category
    namespace_prefix: Angie
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List of Categories
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New Category
            display: [name]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the category \"%object%\"|{ %object%: Category.name }|"
            display: [name]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Category.name }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
