generator: admingenerator.generator.doctrine
params:
    model: Angie\BlogBundle\Entity\Comment
    namespace_prefix: Angie
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
    i18n_catalog: comment
builders:
    list:
        params:
            title: List of Comments
            display: [ post, body, created, updated ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New Comments
            display: [ post, body ]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object"
            display: [ post, body ]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object "
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
