generator: admingenerator.generator.doctrine
params:
    model: Angie\BlogBundle\Entity\Post
    namespace_prefix: Angie
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields: 
        is_published : 
            getter: is_published
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
    i18n_catalog: post
builders:
    list:
        params:
            title: List of Posts
            display: [ title, body , is_published , categories ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New Post
            display: [ title, body , is_published , categories]
            actions:
                #save: ~
                list: ~
                save-and-list: ~ 
            fields:
                categories:
                    formType: entity
                    addFormOptions:
                        class: AngieBlogBundle:Category
                        property: name
                        multiple: true

    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Post.title }|"
            display: [ title, body , is_published , categories ]
            actions:
                save-and-list: ~
                list: ~
            fields:
                categories:
                    formType: entity
                    addFormOptions:
                        class: AngieBlogBundle:Category
                        property: name
                        multiple: true
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Post.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
