angie_admin_comment:
    resource: "@AngieAdminBundle/Controller/Comment/"
    type:     admingenerator
    prefix:   /admin/comments

angie_admin_posts:
    resource: "@AngieAdminBundle/Controller/Post/"
    type:     admingenerator
    prefix:   /admin/posts

angie_admin_categories:
    resource: "@AngieAdminBundle/Controller/Category/"
    type:     admingenerator
    prefix:   /admin/categories

angie_blog:
    resource: "@AngieBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
