angie_blog_hello:
    pattern:  /hello/{name}
    defaults: { _controller: AngieBlogBundle:Default:index }
    
angie_home: 
    pattern :  /
    defaults: { _controller: AngieBlogBundle:Index:index }

angie_post: 
    pattern :  /post/new
    defaults: { _controller: AngieBlogBundle:Post:new }
    
    