parameters:
#    angie_blog.example.class: Angie\BlogBundle\Example

services:
#    angie_blog.example:
#        class: %angie_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
